apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: sanikaparanjpe/flask-repo:server-image-v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000


